set nocompatible "sets Vim to behave differently from Vi"
set tabstop=2 "sets the number of spaces a <Tab> press will make"
set shiftwidth=2 "Text is indented by two spaces with the operations >> and <<, and with autoindent"
set number "sets Vim to display line numbers along the left side of the window"
set ls=2 "sets Vim to show a status line when one window is shown"
set ruler "displays cursor line and column and its percent progess into the text document"
set history=50 "sets command history to be 50 commands long"
set backspace=indent,eol,start "allows backspace to delete autoindents, line breaks, and the start of insert"
set bg=light "sets vim color scheme to colors that suit a light background"
set backup "Vim will create a backup of a file before overwriting that filename and save it"
set backupdir=~/.backup "sets the directory for backup files to ~/.backup"
set directory=~/.vimswap "sets the name of the directory where a swap file for a given file can be found"

set visualbell "disable beeping in vim in WSL linux terminal"
set t_vb=
